Repository HEXRD/hexrd, pull requests merged in 2020-09, with the labels that each got.

#83 New distortion
  hexrd/distortion/__init__.py
  hexrd/distortion/distortionabc.py
  hexrd/distortion/ge_41rt.py
  hexrd/distortion/identity.py
  hexrd/distortion/nyi.py
  hexrd/distortion/registry.py
  hexrd/distortion/utils.py
  hexrd/fitting/grains.py
  hexrd/instrument.py
  hexrd/transforms/xf.py
  hexrd/transforms/xfcapi.py
  hexrd/xrdutil.py
Labels: enhancement, high priority

#96 added LLNL instrument specs
  hexrd/resources/PXRDIP_IMAGE-PLATE-B_bnd.txt
  hexrd/resources/PXRDIP_IMAGE-PLATE-D_bnd.txt
  hexrd/resources/PXRDIP_IMAGE-PLATE-L_bnd.txt
  hexrd/resources/PXRDIP_IMAGE-PLATE-R_bnd.txt
  hexrd/resources/PXRDIP_IMAGE-PLATE-U_bnd.txt
  hexrd/resources/TARDIS_IMAGE-PLATE-2_bnd.txt
  hexrd/resources/TARDIS_IMAGE-PLATE-3_bnd.txt
  hexrd/resources/TARDIS_IMAGE-PLATE-4_bnd.txt
  hexrd/resources/pxrdip_reference_config.yml
  hexrd/resources/tardis_ref_config.yml
Labels: enhancement, high priority

#114 fixed matrixutil deprecations
  hexrd/crystallography.py
  hexrd/matrixutil.py
Labels: enhancement

#125 Material lattice prameter setter
  hexrd/material.py
Labels: bug, high priority
