Repository HEXRD/hexrd, pull requests merged in 2021-12, with the labels that each got.

#360 replace "_" with "" in the HM symbol.
  hexrd/material.py
Labels: enhancement

#362 made master WPPF linter-happy
  hexrd/wppf/WPPF.py
Labels: documentation, cleanup

#363 added docstrings for Euler functions
  hexrd/rotations.py
Labels: documentation

#365 Revert fixed conda version
  .github/workflows/package.yml
Labels: cleanup

#367 Added list sort to deal with glob
  hexrd/imageseries/load/imagefiles.py
  hexrd/xrdutil/utils.py
Labels: enhancement, invalid

#369 Update imagefiles.py
  hexrd/imageseries/load/imagefiles.py
Labels: bug, high priority
