Repository HEXRD/hexrd, pull requests merged in 2021-07, with the labels that each got.

#297 Remove sglite
  hexrd/sglite/Makefile.am
  hexrd/sglite/Makefile.delsci
  hexrd/sglite/Makefile.in
  hexrd/sglite/runtests.c
  hexrd/sglite/setup.py
  hexrd/sglite/sgcb.c
  hexrd/sglite/sgcharmx.c
  hexrd/sglite/sgconst.h
  hexrd/sglite/sgfile.c
  hexrd/sglite/sggen.c
  hexrd/sglite/sgglobal.c
  hexrd/sglite/sghall.c
  hexrd/sglite/sghkl.c
  hexrd/sglite/sglite.h
  hexrd/sglite/sglitemodule.c
  hexrd/sglite/sglitemodule.def
  hexrd/sglite/sgltr.c
  hexrd/sglite/sgmath.c
  hexrd/sglite/sgmetric.c
  hexrd/sglite/sgnorm.c
  hexrd/sglite/sgprop.c
  hexrd/sglite/sgrefset.h
  hexrd/sglite/sgss.c
  hexrd/sglite/sgstr.c
  hexrd/sglite/sgsymbols.c
  hexrd/sglite/sgtidy.c
  hexrd/sglite/sgtype.c
  hexrd/sglite/sgutil.c
  hexrd/spacegroup.py
  setup.py
Labels: cleanup

#298 updated legacy instrument config conversion
  scripts/convert_instrument_config.py
Labels: documentation, enhancement

#304 loosened a cutoff tol and fixed a kwarg
  hexrd/rotations.py
  hexrd/xrdutil/utils.py
Labels: enhancement
