Repository HEXRD/hexrd, pull requests merged in 2021-06, with the labels that each got.

#280 NF Processing and Scripting
  hexrd/grainmap/__init__.py
  hexrd/grainmap/nfutil.py
  hexrd/grainmap/tomoutil.py
  hexrd/grainmap/vtkutil.py
  scripts/preprocess_tomo_mask.py
  scripts/process_nf.py
Labels: HEDM, enhancement

#290 added eta patch specification option
  hexrd/instrument.py
Labels: documentation, enhancement

#296 adjust output of line position extraction
  hexrd/indexer.py
  hexrd/instrument.py
Labels: cleanup, enhancement
