Repository HEXRD/hexrd, pull requests merged in 2021-09, with the labels that each got.

#315 added kwarg for distortion application in cart<->ang transforms
  hexrd/instrument.py
Labels: documentation, enhancement

#318 Update instrument.py
  hexrd/instrument.py
Labels: enhancement, cleanup

#319 Fix cases when the occupancy or the isotropic Debye waller factors are undefined
  hexrd/material.py
Labels: enhancement

#328 swith to using pixel angular gradient arrays
  hexrd/instrument.py
Labels: enhancement, cleanup
