Repository HEXRD/hexrd, pull requests merged in 2021-04, with the labels that each got.

#245 updated reference pxrdip
  hexrd/resources/pxrdip_reference_config.yml
Labels: enhancement

#246 added pixel angle gradients
  hexrd/instrument.py
  hexrd/transforms/xfcapi.py
Labels: enhancement

#248 Memoize the pixel_angles function
  hexrd/instrument.py
  hexrd/utils/decorators.py
  tests/test_memoize.py
Labels: enhancement

#220 Add some basic testing for the Material class
  tests/test_material.py
Labels: documentation, testing

#251 Update instrument.py
  hexrd/instrument.py
Labels: bug

#256 added table of X-ray energies
  hexrd/resources/characteristic_xray_energies.h5
Labels: enhancement
