Repository HEXRD/hexrd, pull requests merged in 2022-02, with the labels that each got.

#396 Fixing write error in material
  hexrd/material.py
Labels: enhancement

#398 Fix multiprocessing context for ProcessPoolExecutor
  hexrd/constants.py
  hexrd/instrument.py
Labels: high priority, cleanup

#401 add tqdm package dependency
  conda.recipe/meta.yaml
  setup.cfg
  setup.py
Labels: enhancement

#403 catch None in hdf5 write as TypeError
  hexrd/instrument.py
Labels: bug

#407 Powder line extraction
  hexrd/calibration/plot_calibration.py
  hexrd/instrument.py
Labels: invalid

#406 Catch for flat patch data
  hexrd/fitting/calibration.py
  hexrd/instrument.py
Labels: bug
