Repository HEXRD/hexrd, pull requests merged in 2022-08, with the labels that each got.

#455 Update spectrum fitting utils to support wildcards in parameter name matching
  hexrd/fitting/utils.py
Labels: documentation, enhancement

#465 replacing "if" with "elif" in line 604 of materials.py.
  hexrd/material.py
Labels: bug

#446 Pinhole distortion
  hexrd/fitting/calibration.py
  hexrd/instrument.py
  hexrd/xrdutil/phutil.py
Labels: enhancement

#454 changed hkl specification for indexing to master hklID
  hexrd/config/findorientations.py
  hexrd/crystallography.py
  hexrd/findorientations.py
  hexrd/indexer.py
  hexrd/instrument.py
  hexrd/xrdutil/utils.py
Labels: documentation, enhancement, high priority, HEDM
